In [105]:
# Read scv
import pandas as pd
df = pd.read_csv("data\steam_games_dataset.csv")
df.head()

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
0,730,Counter-Strike: Global Offensive,Valve,Valve,NaN,7642084,1173003,0,"100,000,000 .. 200,000,000",33852,708,6645,301,0,0,0,1013936
1,1172470,Apex Legends,Respawn,Electronic Arts,NaN,668053,326926,0,"100,000,000 .. 200,000,000",10506,496,935,246,0,0,0,124262
2,578080,PUBG: BATTLEGROUNDS,PUBG Corporation,"KRAFTON, Inc.",NaN,1520457,1037487,0,"100,000,000 .. 200,000,000",23165,717,5622,261,0,0,0,314682
3,1623730,Palworld,Pocketpair,Pocketpair,NaN,358266,22443,0,"50,000,000 .. 100,000,000",3854,835,2213,257,2999,2999,0,18028
4,440,Team Fortress 2,Valve,Valve,NaN,1044264,117208,0,"50,000,000 .. 100,000,000",21244,736,4262,102,0,0,0,43819

In [106]:
# Caculate the positive ratio for each games
df["positive_ratio"] = df["positive"]/(df["positive"]+df["negative"])
df[["name","positive","negative","positive_ratio"]].head()

                               name  positive  negative  positive_ratio
0  Counter-Strike: Global Offensive   7642084   1173003        0.866932
1                      Apex Legends    668053    326926        0.671424
2               PUBG: BATTLEGROUNDS   1520457   1037487        0.594406
3                          Palworld    358266     22443        0.941049
4                   Team Fortress 2   1044264    117208        0.899087

In [ ]:
# Naive ranking based only on positive ratio
df_filtered = df[df["positive"]+df["negative"] > 1000]
df_filtered.sort_values(by="positive_ratio",ascending=False)[["name","positive_ratio"]].head()

                             name  positive_ratio
3473              The WereCleaner        0.994367
9323        A Castle Full of Cats        0.994263
9925  Monster Prom 4: Monster Con        0.993075
5288      Papa's Freezeria Deluxe        0.992576
6955            Patrick's Parabox        0.992174

In [ ]:
# Bayesian-adjusted ranking
C = df["positive_ratio"].mean()
m = 10000
df["bayesian_score"] = ((df["positive"]+C*m)/(df["positive"]+df["negative"]+m))
df.sort_values(by="bayesian_score",ascending=False)[["name","positive_ratio"]].head()

                  name  positive_ratio
172           Portal 2        0.986909
28      Stardew Valley        0.984415
171  People Playground        0.985743
19    Wallpaper Engine        0.980368
141  Vampire Survivors        0.984601

### Insight: A better way to identify the best Steam games

Simply ranking games by positive review ratio can be misleading, because games with very few reviews may appear at the top. To address this, I used a Bayesian-style score that combines review ratio with review volume. This produces a more reliable ranking and highlights games that are both highly rated and widely reviewed.